name: baseflow_plugin_template
description: A template for plugin examples
version: 2.1.2
repository: https://github.com/Baseflow/baseflow_plugin_template

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/poweredByBaseflow.png
